services:
  discord_bot:
    build: .
    container_name: nhp-bot
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      TZ: UTC
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 128M
